version: '3.8'

services:
  cardjacker:
    image: athack-ctf/chall2025-cardjacker:latest
    hostname: cardjacker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2025:2025"
